### PR TITLE
Changes to siteID 53 year 1988

### PR DESCRIPTION
**Pull request by gdicecco**
* Text recognition errors in siteID 53, year 1988 in bbc_counts.csv
* Corrected species and counts from 1988 BBC PDF

### CODE REVIEW

**Comment by ethanwhite** [comment]
Thanks @gdicecco!

**Comment by ethanwhite** [comment]
The diff is showing as changing every line in the file. I've tried controlling for line ending differences but that doesn't seem to fix it. What change are you seeing in the diff on your local machine?

**Comment by gdicecco** [comment]
Whoops I'm seeing the same thing, I think this is because I replaced the file in the forked repo with one I had previously edited instead of making the edits after branching. Ignore this and I'll resubmit a version in the right order of steps.
________________________________

**Comment by ethanwhite** [comment]
Sounds great. Thanks!

**Pull request closed without merging**
